# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "colorize", "~> 0.8.1"

gem "artii", "~> 2.1"

gem "tty-prompt", "~> 0.23.1"

gem "ruby-progressbar", "~> 1.11"

gem "json", "~> 2.5"

gem "terminal-table", "~> 3.0"

gem "tty-box", "~> 0.7.0"

gem "require_all", "~> 3.0"
